# Generated by Django 4.2.5 on 2023-09-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acharyaa', '0003_enrollment_duedate_enrollment_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='SelectMembershipPlain',
            new_name='SelectMembershipPlan',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='TimeStamp',
            new_name='timeStamp',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='DOB',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='PhoneNumber',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Reference',
            field=models.CharField(max_length=55),
        ),
    ]
