# Generated by Django 4.2.5 on 2023-09-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acharyaa', '0004_rename_selectmembershipplain_enrollment_selectmembershipplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('imag', models.ImageField(upload_to='photos')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
