# Generated by Django 4.2.5 on 2023-09-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acharyaa', '0005_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='imag',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
