# Generated by Django 4.2.5 on 2023-09-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acharyaa', '0006_alter_gallery_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='imag',
            new_name='img',
        ),
    ]
